apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: za689jevu-python 
  janus-idp.io/tekton: za689jevu-python
  backstage.io/kubernetes-id: za689jevu-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: za689jevu-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml